title: Fabien Rouault
logo: /assets/img/Photo_profil.png
description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
